# Generated by Django 4.0.4 on 2022-05-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat.chat'),
        ),
    ]
