# Generated by Django 4.0.4 on 2022-05-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_image_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded',
            field=models.DateTimeField(blank=True),
        ),
    ]
